[theme]
base                     = "dark"
primaryColor             = "#00A8FF"
backgroundColor          = "#060B14"
secondaryBackgroundColor = "#0D1526"
textColor                = "#E8F4FF"
font                     = "sans serif"
